### ISSUE TITLE
Quels package python à installer pour les librairies utilisées?

### ISSUE THREAD

**Issue by TDraGoNoiR** [fabriceDurand/QRCODE#1]
Bonjour Fabrice, dans ta vidéo que j'ai trouvé intéressant pour débuter sur les QRCode, il manque un peut explication sur les packages à installer dans Python pour l'utilisation. Par exemple j'ai une erreur sur la commande Import cv2 et je ne sais pas quel package installer. Je suppose que c'est de même pour : 
import cv2
import numpy 
import decode
import date, datetime

**Comment by dfdurand** [comment]
- CV2  -> pip install opencv-python   

en installant cela , normalement tu as numpy avec , sinon  : pip install numpy
date et datetime  sont des librairies natives à python.

Merci de m'avoir notifier et j'espère que cela vous sera utile
